### ISSUE TITLE
[Feature] Create the ERDs for the given forms

### ISSUE THREAD

**Issue by shahzebsiddiq** [codeforpakistan/E-Abyana-Payment-Collection-System-#2]
Create ERDs of the forms given by the department

**Comment by mianabbas2023** [comment]
![WhatsApp Image 2024-11-08 at 10 52 59 AM](https://github.com/user-attachments/assets/fe2522e8-7858-48fe-8501-56dfe9f6843d)

**Comment by mianabbas2023** [comment]
DataBase Diagram
<img width="1253" alt="Screenshot 2024-11-08 at 10 59 52 AM" src="https://github.com/user-attachments/assets/c53331bf-673c-4996-adec-4deb68dbd94e">

**Comment by mianabbas2023** [comment]
![drawSQL-image-export-2024-12-04 (1)](https://github.com/user-attachments/assets/de700ef3-0191-4ac3-95dc-38be2712d4c2)
The login_user table contains user-related details such as user_name, user_email, user_password, and phone number (user_phone_no). It has foreign key relationships with roles, district, division, and halqa, allowing the user to be associated with specific roles and locations.
The Roles table manages user roles and includes a primary key (roles_id) and a role name (roles_name).
The permission table stores permissions, which are linked to roles through the assign_permission table. This setup provides role-based access control.

**Comment by mianabbas2023** [comment]
All APIs

- [ ] Login
- 1. Login for Super Admin
Make sure the Super Admin has a unique identifier, either in the users table or in a separate roles table. The Super Admin role can be assigned when the first user is creat.
2. Creating Admins
Once the Super Admin logs in, they should be able to create Admin1, Admin2, and Admin3 users. You can implement this in the following way:

Role Creation: Assign roles like "Admin1", "Admin2", and "Admin3" to the users.
Permissions: Depending on what you want each admin to be able to do, assign appropriate permissions.

- [ ] Divsion
A Division is an organizational unit that represents a large geographic or administrative area. It is typically used to group smaller units (like districts or tehsils) for better management and resource allocation. Divisions can also help in structuring data, assigning permissions, and controlling access in a project.

- [ ] District
A District is a secondary-level administrative unit in a hierarchical system, below the division. It plays a vital role in organizing and managing resources, services, and data specific to its area. Each district can further include smaller units such as Tehsils or Villages for detailed management.

- [ ] Tehsil
A Tehsil is the third level of administration in a hierarchy that begins with a Division and District. It helps in managing resources, allocating services, and organizing data at a micro level. Tehsils often act as a bridge between the district-level administration and the smaller units like Villages.

- [ ] Halqa
A Halqa is an administrative or geographical division used for focused management and organization. It is designed to group individuals or areas within a Tehsil, often for administrative ease, voting, or distribution of resources. In rural areas, a Halqa might correspond to a group of villages, while in urban areas, it could represent a neighborhood or block.

- [ ] Village
A Village represents a small community or locality that serves as the base unit for administrative and resource management. Villages are often grouped under a Tehsil or a Halqa, and they form the foundation for various operations like resource allocation, governance, and data collection.
