### ISSUE TITLE
Working on Database Design

### ISSUE THREAD

**Issue by shahzebsiddiq** [codeforpakistan/E-Abyana-Payment-Collection-System-#4]
Working on Database design

- [ ] Creating Tables
- [ ] Connect Tables where needed

**Comment by mianabbas2023** [comment]
![WhatsApp Image 2024-10-22 at 3 27 44 PM (1)](https://github.com/user-attachments/assets/4fd2116a-2257-4357-972f-ad4f05b8998a)

**Comment by mianabbas2023** [comment]
![Uploading Screenshot 2024-10-28 at 12.32.34 PM.png…]()

**Comment by mahnoorcodeforpakistan** [comment]
I have created the district table in the database. This table will help manage and organize district-related data for the Abyana water billing system.
I have attached a screenshot of the database.

**Database**

![WhatsApp Image 2024-10-28 at 12 41 46 PM](https://github.com/user-attachments/assets/16ca3ef7-117f-4936-9ace-e6e6eb45cf08)

**Functional Design**

![WhatsApp Image 2024-10-28 at 12 41 47 PM](https://github.com/user-attachments/assets/8cc8bfd3-3bc0-406d-b8e4-a503c5d41714)

**Comment by mianabbas2023** [comment]
I have created the tehsil table in the database, which will help manage and organize tehsil-related data for the Abyana water billing system.

Additionally, I have added a dropdown menu in the tehsil form that displays the available districts. The selected district from the dropdown is now stored in the database.
<img width="1230" alt="Screenshot 2024-10-28 at 1 02 59 PM" src="https://github.com/user-attachments/assets/14638570-0421-41ff-970e-d6e4958d1aff">
I have attached a screenshot of the database.

**Comment by mianabbas2023** [comment]
Functional Design

<img width="1193" alt="Screenshot 2024-10-28 at 1 02 16 PM" src="https://github.com/user-attachments/assets/9f9c99bc-ee26-4076-ab5a-4c51b647548f">

**Comment by mianabbas2023** [comment]
I have created the village table in the database, which will help manage and organize tehsil-related data for the Abyana water billing system.

Additionally, I have added a dropdown menu in the village form that displays the available tehsils. The selected tehsil
<img width="1217" alt="Screenshot 2024-10-28 at 2 17 40 PM" src="https://github.com/user-attachments/assets/d7b4e299-b888-4730-98e5-f8214f4d5a0b">
 from the dropdown is now stored in the database.

**Comment by mianabbas2023** [comment]
I have created the canal table in the database, which will help manage and organize canal-related data for the Abyana water billing system.

Additionally, I have added a dropdown menu in the Canal form that displays the available Outlet. The selected Outlet from the dropdown is now stored in the database.
<img width="1268" alt="Screenshot 2024-11-03 at 1 07 24 PM" src="https://github.com/user-attachments/assets/fac151ce-93b9-42b1-ae97-8826ffc5f90d">

**Comment by mianabbas2023** [comment]
Created a login table in the database and developed an API to handle login functionality.
<img width="1255" alt="Screenshot 2024-11-06 at 9 20 21 AM" src="https://github.com/user-attachments/assets/c954f2d0-0fe6-4b08-9773-fd1daf657d0e">

**Comment by mianabbas2023** [comment]
Local Login Api 
http://127.0.0.1:8000/api/login
Server  Login Api
https://testproject.famzhost.com/api/login
